---
#TODO: When the time comes, split this file in different roles
#TODO: Create dynamic inventory using nmap to find RPIs on the network (using their mac adresses), and a redis/consul/etcd shared truth
#- hosts: cleanrpi
#  gather_facts: no
#  roles:
#    #Minimal config
#    - role: setup


- hosts: cluster
  #  gather_facts: no
  roles:
    #    - role: keys
    #    - role: basic-config
    #    - role: swarm
    - role: master-setup

