---
# tasks file for gluster

#####################
#Installing software#
#####################
#- name: Update repositories cache and install gluster server and client
#  become: yes
#  apt:
#    name: ['glusterfs-server', 'glusterfs-client']
#    update_cache: yes
#    cache_valid_time: 3600

#- name: enable service glusterfs
#  systemd:
#    name: glusterd
#    #scope: user
#    state: started
#    enabled: yes
#    masked: no
#  become: yes
#
#- name: Ansible register variable basic example
#  shell: "blkid -o export /dev/mmcblk0p3"
#  register: blkid_output
#  become: true
#  changed_when: False
#
#- name: Display partuid of data partition
#  debug:
#    var: blkid_output["stdout_lines"]
#
#- name: Add folder for glusterfs mount
#  become: yes
#  file:
#    path: "/shared/mmcblk0p3"
#    owner: "root"
#    group: "docker"
#    state: directory
#
#- name: Mount up device by PARTUID
#  mount:
#    path: /shared/mmcblk0p3
#    src: "{{ blkid_output['stdout_lines'][3] }}"
#    fstype: ext4
#    opts: defaults
#    state: mounted
#    backup: yes
#  become: yes
#
#- name: Add folder for glusterfs brick
#  become: yes
#  file:
#    path: "/shared/mmcblk0p3/brick"
#    owner: "root"
#    group: "docker"
#    state: directory

- name: Display result of inventory_hostname
  set_fact:
    next_node: "{{ 'etrnl-%03d.local' | format(inventory_hostname | regex_replace('^etrnl-(\\d*).local$', '\\1') | int + 1) }}"

- name: Display partuid of data partition
  debug:
    var: next_node

- name: Glusterfs peer probe
  shell: "gluster peer probe {{ next_node }}"
  register: gluster_probe_output
  become: true

    #- name: "Example2: Add fstab line for shared data partition"
    #  become: yes
    #  lineinfile:
    #    path: /etc/fstab
    #    line: "{{ blkid_output['stdout_lines'][3] }}  /shared/mmcblk0p3 ext4 defaults 0 0"
    #    state: present
    #    backup: yes
    #  register: example2out

