---
# tasks file for swarm
#
####################
#Init or join swarm#
####################
#
#
- name: Join an existing swarm
  docker_swarm:
    state: join
    advertise_addr: eth0
    join_token: SWMTKN-1-2qenpoezm7ztklufmj9ewsbp2qgn56irbmqjjuicpxybcfpgym-6lcqmpmyrx9wh6elhv3r4pkxs
    remote_addrs: [ '192.168.1.8:2377' ]
