---
# vars file for basic-config
links_to_create :
  - { dest: '{{ HOME }}/.bashrc', src: '{{ CONFIG_PERSO }}/bash_config/bashrc' }
  - { dest: '{{ HOME }}/.bash_aliases', src: '{{ CONFIG_PERSO }}/bash_config/bash_aliases' }
  - { dest: '{{ HOME }}/.profile', src: '{{ CONFIG_PERSO }}/bash_config/profile' }
  - { dest: '{{ HOME }}/.bash_funcs', src: '{{ CONFIG_PERSO }}/bash_config/bash_funcs' }
  - { dest: '{{ HOME }}/.bash_completion', src: '{{ CONFIG_PERSO }}/bash_config/bash_completion' }
  - { dest: '{{ HOME }}/.bash_logout', src: '{{ CONFIG_PERSO }}/bash_config/bash_logout' }
  - { dest: '{{ HOME }}/.config/vifm', src: '{{ CONFIG_PERSO }}/vifm' }

# Not used yet
links_to_create_sudo :
  - { dest: '/usr/share/bash-completion/completions/qrpass', src: '{{ CONFIG_PERSO }}/pass/qrpass' }
  - { dest: '/usr/local/bin/spass', src: '{{ HOME }}/.config/perso/pass/spass' }
  - { dest: '/usr/bin/vifmi', src: '/home/alex/.config/perso/vifm/scripts/vifmrun' }


