---
# tasks file for setup
- name: Wait 120 seconds for target connection to become reachable/usable
  wait_for_connection:

##################
#Users and groups#
##################
- name: Ensure groups ansible and docker exist
  become: yes
  group:
    name: "{{ item }}"
    state: present
  with_items:
    - ansible
    - docker

- name: Load passwords from the encrypted vault file
  include_vars:
    file: passwords/passwords.yml
  name: passwords_pi

- name: Load passwords from the encrypted vault file
  include_vars:
    file: passwords/passwords.yml
  name: passwords_main_user

- name: Load salt from the encrypted vault file
  include_vars:
    file: passwords/passwords.yml
  name: passwords_salt

- name: Create users
  become: yes
  user:
    name: "alex"
    password: "{{ passwords_main_user | password_hash('sha512', passwords_salt) }}"
    skeleton: "/etc/skel"
    shell: /bin/bash
    groups: ansible, docker, sudo   # Empty by default.

- name: Set authorized key, removing all the authorized keys already set
  authorized_key:
    user: "alex"
    key: "{{ lookup('file', '{{ HOME }}/.ssh/id_ecdsa.pub') }}"
    state: present
    exclusive: True
  become: yes

#######################
#Set hostnames and IPs#
#######################
- name: Changes the hostname (without needing to restart)
  become: yes
  hostname:
    name: '{{ DESTINATION_NAME }}'

- name: Updates nodes name in hosts file
  become: yes
  lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: '127.0.1.1 {{ DESTINATION_NAME }}'
    owner: root
    group: root
    mode: 0644

- name: Updates nodes name in hostname file
  become: yes
  lineinfile:
    path: /etc/hostname
    regexp: '^.*'
    line: '{{ DESTINATION_NAME }}'
    owner: root
    group: root
    mode: 0644

- name: Creates a link to update timezone
  become: yes
  file:
    src: /usr/share/zoneinfo/Europe/Paris
    dest: /etc/localtime
    state: link

- name: Changes the password of user pi for added security
  become: yes
  user:
    name: pi
    update_password: always
    password: "{{ passwords_pi | password_hash('sha512', passwords_salt) }}"



- meta: end_play    #Usefull for dev: ends the play right here

- name: Reboot node and stop polling.
  shell: reboot
  become: yes
  async: 10 # Do not care for 10 sec
  poll: 0 # Fire & Forget

