---
# tasks file for keys
- name: Wait 120 seconds for target connection to become reachable/usable
  wait_for_connection:


#####
#GPG#
#####

- name: Update repositories cache and install usefull packages
  become: yes
  apt:
    name: ['gpg']
    update_cache: yes
    cache_valid_time: 3600

- name: Copy gpg key from local to host, needed to decrypt pass files
  copy:
    src: /home/alex/.gpg
    dest: "{{ HOME }}"
    owner: alex
    group: alex
    mode: '0744'
  register: new_key


- name: import public key
  shell: gpg --import {{ HOME }}/.gpg/basekey.gpg
  when: new_key.changed

- name: Load masterpass from an encrypted file
  include_vars:
    file: masterpass/masterpass.yml
  name: masterpass

- name: import private key
  shell: gpg --batch --allow-secret-key-import --passphrase "{{ masterpass }}" --import {{ HOME }}/.gpg/basekey_sec.gpg
  when: new_key.changed

#####
#SSH#
#####

- name: Create keys directory
  become: yes
  file:
    path: "{{ HOME }}/.ssh/keys"
    group: alex
    owner: alex
    mode: "0755"
    state: directory

    #- name: Display paths of all .txt files in dir
    #  debug: msg={{ lookup('fileglob', '/home/alex/.ssh/keys/*.priv') }}
    #
    #- name: Display paths of all non public files in dir
    #  debug: msg={{ lookup('fileglob', '/home/alex/.ssh/keys/*.pub') }}

    #- meta: end_play    #Usefull for dev: ends the play right here

- name: Copy public ssh deploy key from local to host, needed to clone configs
  copy:
    src: "{{ item }}"
    dest: "{{ HOME }}/.ssh/keys/{{ item | basename }}"
    owner: alex
    group: alex
    mode: '0755'
  with_fileglob:
    - '/home/alex/.ssh/keys/*.pub'

- name: Copy private ssh deploy key from local to host, needed to clone configs
  copy:
    src: "{{ item }}"
    dest: "{{ HOME }}/.ssh/keys/{{ item | basename }}"
    owner: alex
    group: alex
    mode: '0600'
  with_fileglob:
    - '/home/alex/.ssh/keys/*.priv'

- name: Make sure the known hosts file exists
  file:
    path: "{{ ssh_known_hosts_file }}"
    state: file
    owner: alex
    group: alex
    mode: '0644'

- name: Check host name availability
  shell: "ssh-keygen -f {{ ssh_known_hosts_file }} -F {{ item }}"
  loop: "{{ ssh_known_hosts }}"
  register: ssh_known_host_results
  ignore_errors: yes
  changed_when: False

- name: Scan the public key
  shell: "{{ ssh_known_hosts_command}} {{ item.item }} >> {{ ssh_known_hosts_file }}"
  with_items: "{{ ssh_known_host_results.results }}"
  when: item.stdout == ""

- meta: end_play    #Usefull for dev: ends the play right here
